apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: itw-custom
spec:
  rules:
  - host: isterryworkingtoday.com
    http:
      paths:
      - backend:
          serviceName: itw
          servicePort: 80
